import { DreamieStatsCodex, Rarity } from "./typesAndUtils";

export const dreamieCodex: { [key: string]: DreamieStatsCodex } = {
	// active
	"Lapis Lazuli": { beauty: 66, cuteness: 108, strength: 48, wisdom: 78, rarity: Rarity.Legendary },
	"Little Bean": { beauty: 60, cuteness: 108, strength: 66, wisdom: 66, rarity: Rarity.Legendary },
	"Angel of Time": { beauty: 114, cuteness: 60, strength: 72, wisdom: 54, rarity: Rarity.Legendary },
	"Vampire": { beauty: 60, cuteness: 72, strength: 48, wisdom: 120, rarity: Rarity.Legendary },
	"Shura": { beauty: 72, cuteness: 54, strength: 108, wisdom: 66, rarity: Rarity.Legendary },
	"Little Red Riding Hood": { beauty: 120, cuteness: 48, strength: 66, wisdom: 66, rarity: Rarity.Legendary },
	"Master of Qigong": { beauty: 66, cuteness: 66, strength: 96, wisdom: 72, rarity: Rarity.Legendary },
	"Retired Witch": { beauty: 54, cuteness: 36, strength: 96, wisdom: 54, rarity: Rarity.Epic },
	"Drawing Assistant": { beauty: 54, cuteness: 84, strength: 42, wisdom: 60, rarity: Rarity.Epic },
	"Nun": { beauty: 48, cuteness: 42, strength: 54, wisdom: 96, rarity: Rarity.Epic },
	"Idol": { beauty: 90, cuteness: 48, strength: 42, wisdom: 60, rarity: Rarity.Epic },
	"Aladdin": { beauty: 24, cuteness: 36, strength: 72, wisdom: 48, rarity: Rarity.Rare },
	"Bald-Hero": { beauty: 42, cuteness: 36, strength: 54, wisdom: 48, rarity: Rarity.Rare },
	// passive
	"Sarcastic Woman": { beauty: 66, cuteness: 60, strength: 66, wisdom: 108, rarity: Rarity.Legendary },
	"Green Archer": { beauty: 54, cuteness: 72, strength: 108, wisdom: 66, rarity: Rarity.Legendary },
	"Cactus": { beauty: 48, cuteness: 78, strength: 108, wisdom: 66, rarity: Rarity.Legendary },
	"Blood Transfusion Girl": { beauty: 42, cuteness: 108, strength: 54, wisdom: 96, rarity: Rarity.Legendary },
	"One-Eyed King": { beauty: 60, cuteness: 60, strength: 108, wisdom: 72, rarity: Rarity.Legendary },
	"Eclipse": { beauty: 54, cuteness: 108, strength: 96, wisdom: 42, rarity: Rarity.Legendary },
	"Nobble Doll": { beauty: 60, cuteness: 120, strength: 72, wisdom: 48, rarity: Rarity.Legendary },
	"Clown": { beauty: 42, cuteness: 60, strength: 78, wisdom: 60, rarity: Rarity.Epic },
	"Swine King": { beauty: 48, cuteness: 66, strength: 78, wisdom: 48, rarity: Rarity.Epic },
	"Fantasy Witch": { beauty: 54, cuteness: 90, strength: 60, wisdom: 36, rarity: Rarity.Epic },
	"Evil King Envoy": { beauty: 90, cuteness: 48, strength: 60, wisdom: 42, rarity: Rarity.Epic },
	"Duelist": { beauty: 54, cuteness: 60, strength: 42, wisdom: 84, rarity: Rarity.Epic },
	"Soul Puppet": { beauty: 54, cuteness: 48, strength: 36, wisdom: 42, rarity: Rarity.Rare },
	"Pochi-chan": { beauty: 42, cuteness: 24, strength: 30, wisdom: 24, rarity: Rarity.Common },
	"Whoa": { beauty: 36, cuteness: 18, strength: 24, wisdom: 42, rarity: Rarity.Common },
	"Rhino Beetle": { beauty: 24, cuteness: 36, strength: 42, wisdom: 18, rarity: Rarity.Common },
	// dispatch
	"Cheongsam Rabbit": { beauty: 72, cuteness: 120, strength: 72, wisdom: 36, rarity: Rarity.Legendary },
	"Singer": { beauty: 66, cuteness: 54, strength: 72, wisdom: 108, rarity: Rarity.Legendary },
	"Bear Doll": { beauty: 66, cuteness: 54, strength: 108, wisdom: 72, rarity: Rarity.Legendary },
	"Musician": { beauty: 120, cuteness: 78, strength: 42, wisdom: 60, rarity: Rarity.Legendary },
	"Pu'er Tea": { beauty: 36, cuteness: 90, strength: 48, wisdom: 66, rarity: Rarity.Epic },
	"Detective": { beauty: 42, cuteness: 54, strength: 48, wisdom: 96, rarity: Rarity.Epic },
	"Big Bear": { beauty: 60, cuteness: 24, strength: 90, wisdom: 66, rarity: Rarity.Epic },
	"Raccoon": { beauty: 84, cuteness: 60, strength: 60, wisdom: 36, rarity: Rarity.Epic },
	"Capybara": { beauty: 42, cuteness: 60, strength: 36, wisdom: 42, rarity: Rarity.Rare },
	"Silent One": { beauty: 54, cuteness: 30, strength: 30, wisdom: 66, rarity: Rarity.Rare },
	"Dragon Maid": { beauty: 36, cuteness: 30, strength: 60, wisdom: 54, rarity: Rarity.Rare },
	"Four-Leaf Clover": { beauty: 54, cuteness: 30, strength: 48, wisdom: 48, rarity: Rarity.Rare },
	"Cutie": { beauty: 24, cuteness: 42, strength: 18, wisdom: 36, rarity: Rarity.Common },
	"Inventor": { beauty: 30, cuteness: 30, strength: 18, wisdom: 42, rarity: Rarity.Common },
	"Mechanic": { beauty: 30, cuteness: 30, strength: 42, wisdom: 18, rarity: Rarity.Common },
	"Fortune Teller": { beauty: 42, cuteness: 30, strength: 30, wisdom: 18, rarity: Rarity.Common },
	// attributes
	"Expressive Priest": { beauty: 120, cuteness: 48, strength: 66, wisdom: 66, rarity: Rarity.Legendary },
	"Cheese Lover": { beauty: 54, cuteness: 48, strength: 84, wisdom: 114, rarity: Rarity.Legendary },
	"Xue Ji": { beauty: 60, cuteness: 72, strength: 60, wisdom: 108, rarity: Rarity.Legendary },
	"White Duck": { beauty: 72, cuteness: 48, strength: 72, wisdom: 108, rarity: Rarity.Legendary },
	"Purple Bomb": { beauty: 102, cuteness: 60, strength: 60, wisdom: 78, rarity: Rarity.Legendary },
	"Incubator": { beauty: 48, cuteness: 90, strength: 54, wisdom: 48, rarity: Rarity.Epic },
	"Little Treant": { beauty: 60, cuteness: 90, strength: 48, wisdom: 42, rarity: Rarity.Epic },
	"Frost Angel": { beauty: 96, cuteness: 66, strength: 30, wisdom: 48, rarity: Rarity.Epic },
	"Sunflower": { beauty: 60, cuteness: 48, strength: 36, wisdom: 36, rarity: Rarity.Rare },
	"Magician": { beauty: 48, cuteness: 54, strength: 48, wisdom: 30, rarity: Rarity.Rare },
	"Magical Girl": { beauty: 48, cuteness: 30, strength: 36, wisdom: 66, rarity: Rarity.Rare },
	"Crimson Lotus": { beauty: 24, cuteness: 60, strength: 66, wisdom: 30, rarity: Rarity.Rare },
	"Little Policewoman": { beauty: 72, cuteness: 30, strength: 36, wisdom: 42, rarity: Rarity.Rare },
	"Witch": { beauty: 24, cuteness: 36, strength: 42, wisdom: 18, rarity: Rarity.Common },
	"Administrator": { beauty: 36, cuteness: 42, strength: 24, wisdom: 18, rarity: Rarity.Common },
	"Psychic": { beauty: 18, cuteness: 36, strength: 18, wisdom: 48, rarity: Rarity.Common },
	"The Naive": { beauty: 42, cuteness: 30, strength: 18, wisdom: 30, rarity: Rarity.Common },
};